/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_trinfin_cryptolibrary_clsCrypto */

#ifndef _Included_com_sis_mtrainer_server_clsCrypto
#define _Included_com_sis_mtrainer_server_clsCrypto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_trinfin_cryptolibrary_clsCrypto
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sisindia_ai_mtrainer_android_features_server_clsCrypto_stringFromJNI(JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_sisindia_ai_mtrainer_android_features_server_clsCrypto_CEncryptString(JNIEnv *, jobject,jstring);

JNIEXPORT jstring JNICALL Java_com_sisindia_ai_mtrainer_android_features_server_clsCrypto_CDecryptString(JNIEnv *, jobject,jstring);

JNIEXPORT jbyteArray JNICALL Java_com_sisindia_ai_mtrainer_android_features_server_clsCrypto_Encrypt(JNIEnv *, jobject,jbyteArray);

JNIEXPORT jbyteArray JNICALL Java_com_sisindia_ai_mtrainer_android_features_server_clsCrypto_Decrypt(JNIEnv *, jobject,jbyteArray,jstring key);


#ifdef __cplusplus
}
#endif
#endif
